# Generated by Django 4.0.1 on 2022-01-11 07:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(choices=[('HM', 'Hospital Manager'), ('HI', 'Hospital IT'), ('FI', 'Financial'), ('BO', 'Business Onwer'), ('OT', 'Other')], default='OT', max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/photo/')),
            ],
            options={
                'verbose_name': 'Clinet',
                'verbose_name_plural': 'Clinets',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('A', 'About'), ('H', 'Home'), ('F', 'Feature'), ('B', 'Blog'), ('G', 'Gallery'), ('C', 'Contact'), ('P', 'Privacy'), ('T', 'Term & Conditions'), ('O', 'Other')], default='O', max_length=1)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_valied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.text')),
            ],
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('P', 'Phone'), ('M', 'Mobile'), ('F', 'Fax'), ('O', 'Other')], default='O', max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(choices=[('OA', 'Bahah'), ('DA', 'Dammam'), ('DH', 'Dhahran'), ('HA', "Ha'il"), ('JE', 'Jeddah'), ('RI', 'Riyadh'), ('JI', 'Jizan'), ('KH', 'Khobar'), ('JU', 'Jubail'), ('MD', 'Medina'), ('MC', 'Mecca'), ('QA', 'Qatif'), ('TA', 'Taif'), ('TA', 'Tabuk'), ('UN', 'Unaizah'), ('YA', 'Yanbu'), ('OT', 'Other')], default='RI', max_length=2)),
                ('province', models.CharField(choices=[('MC', 'Mecca'), ('RI', 'Riyadh'), ('ES', 'Eastern'), ('NO', 'Northern'), ('AS', 'Asir'), ('JI', 'Jizan'), ('MD', 'Medinah'), ('QA', 'AL-Qassim'), ('TA', 'Tabuk'), ('ON', "Ha'il"), ('NA', 'Najran'), ('JA', 'AL-Jawf'), ('SK', 'Al-Bahah')], default='RI', max_length=2)),
                ('country', models.CharField(choices=[('SA', 'Saudi Arabia'), ('UE', 'united Emirates'), ('KW', 'kuwait'), ('OT', 'Other')], default='SA', max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('address_type', models.CharField(choices=[('H', 'Home'), ('B', 'Billing'), ('W', 'Work')], default='H', max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
    ]
