# Generated by Django 4.0.1 on 2022-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'finance', 'verbose_name_plural': 'finance'},
        ),
        migrations.AlterField(
            model_name='pay',
            name='file_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='file id'),
        ),
    ]
