# Generated by Django 4.0.1 on 2022-01-12 00:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
    ]
