# Generated by Django 4.0.1 on 2022-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='file_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='file id'),
        ),
    ]
