# Generated by Django 4.0.1 on 2022-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst',
            name='category',
            field=models.CharField(choices=[('GE', 'General'), ('AB', 'Abdominal'), ('BR', 'Breast imaging'), ('CA', 'Cardiovascular'), ('CH', 'Chest'), ('EM', 'Emergency'), ('HE', 'Head and neck'), ('IN', 'Interventional'), ('MU', 'Musculoskeletal'), ('NE', 'Neuroradiology'), ('NU', 'Nuclear'), ('PE', 'Pediatric'), ('RA', 'Radiation oncology'), ('VA', 'Vascular'), ('OT', 'Other')], default='GE', max_length=2, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='analyst',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='analyst',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='sex'),
        ),
    ]
