# Generated by Django 4.0.1 on 2022-01-11 07:19

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
                ('admission', models.CharField(choices=[('FM', 'Family medicine'), ('SU', 'Surgery'), ('DE', 'Dermatopathology'), ('EM', 'Emergency medicine'), ('GE', 'General'), ('OB', 'Obstetrics and gynecology'), ('OT', 'Other')], default='OT', help_text='main admission department', max_length=2)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='medicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Age has to be below 100'), django.core.validators.MinValueValidator(1, message='Age has to be above 1')])),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_married', models.BooleanField(default=False)),
                ('is_smoking', models.BooleanField(default=False)),
                ('medical_history', models.TextField(blank=True, help_text='list all previous health conditions', null=True)),
                ('family_history', models.TextField(blank=True, help_text='liat all family-related health conditions', null=True)),
                ('complain', models.TextField(blank=True, help_text='the current complain that patient has', null=True)),
                ('medison', models.TextField(blank=True, help_text='list all medisons that patient has', null=True)),
                ('allergy', models.TextField(blank=True, help_text='list all allergies that patient has', null=True)),
                ('pateint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
            ],
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
    ]
