# Generated by Django 4.0.1 on 2022-01-24 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalprofile',
            options={'verbose_name': 'medical profile', 'verbose_name_plural': 'medical profiles'},
        ),
        migrations.RemoveField(
            model_name='medicalprofile',
            name='pateint',
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Age has to be below 100'), django.core.validators.MinValueValidator(1, message='Age has to be above 1')], verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='allergy',
            field=models.TextField(blank=True, help_text='list all allergies that patient has', null=True, verbose_name='allergy'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='complain',
            field=models.TextField(blank=True, help_text='the current complain that patient has', null=True, verbose_name='complain'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='family_history',
            field=models.TextField(blank=True, help_text='liat all family-related health conditions', null=True, verbose_name='family history'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='file_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='file id'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='is_married',
            field=models.BooleanField(default=False, verbose_name='married'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='is_smoking',
            field=models.BooleanField(default=False, verbose_name='smoking'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='medical_history',
            field=models.TextField(blank=True, help_text='list all previous health conditions', null=True, verbose_name='medical history'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='medison',
            field=models.TextField(blank=True, help_text='list all medisons that patient has', null=True, verbose_name='medison'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='sex'),
        ),
    ]
