# Generated by Django 4.0.1 on 2022-01-11 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Notes')),
                ('category', models.CharField(choices=[('H', 'Hospital'), ('M', 'Meeting'), ('D', 'Doctor'), ('P', 'Pharmacy'), ('A', 'Analyst'), ('O', 'Other')], default='H', help_text='Booking an appointment for', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('H', 'Hold'), ('D', 'Declined'), ('R', 'Archived')], default='H', max_length=1)),
                ('assgnied_for', models.ForeignKey(blank=True, help_text='the doctor responsible for the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_for', to=settings.AUTH_USER_MODEL)),
                ('assgnied_to', models.ManyToManyField(blank=True, help_text='the patient(s) attending the appointment', null=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Schedules',
            },
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
    ]
