# Generated by Django 4.0.1 on 2022-01-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='availability',
            field=models.CharField(choices=[('O', 'off-work'), ('F', 'free'), ('B', 'busy')], default='B', max_length=1),
        ),
    ]
