# Generated by Django 4.0.1 on 2022-01-11 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0002_event_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assgnied_to',
            field=models.ManyToManyField(help_text='the patient(s) attending the appointment', related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
